=== AlbertBeto/XML/SegundoEjercicio/facturator.dtd
<!ELEMENT facturaTipo (factura+)>
<!ELEMENT factura (datos_empresa,datos_cliente,datos_factura)>
<!ELEMENT datos_empresa (nombre, dir,poblacion, codigo_postal,provincia, cif, telefono, fax)>
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT dir (#PCDATA) >
<!ELEMENT poblacion (#PCDATA) >
<!ELEMENT codigo_postal (#PCDATA) >
<!ELEMENT provincia (#PCDATA) >
<!ELEMENT cif (#PCDATA) >
<!ELEMENT telefono (#PCDATA) >
<!ELEMENT fax (#PCDATA) >

<!ELEMENT datos_cliente (nombre, dir_env,poblacion, codigo_postal,provincia)>

<!ELEMENT dir_env (#PCDATA) >

<!ELEMENT datos_factura (fecha,linea+,base,cuota_iva,total)>
<!ELEMENT fecha (#PCDATA) >

<!ELEMENT linea (referencia,descripcion,cantidad,precio,importe) >
    <!ELEMENT referencia (#PCDATA) >
    <!ELEMENT descripcion (#PCDATA) >
    <!ELEMENT cantidad (#PCDATA) >
    <!ELEMENT precio (#PCDATA) >
    <!ELEMENT importe (#PCDATA) >

<!ELEMENT base (#PCDATA) >
<!ELEMENT cuota_iva (#PCDATA) >
<!ELEMENT total (#PCDATA) >

=== AlbertBeto/XML/SegundoEjercicio/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturaTipo SYSTEM "facturator.dtd">
<factura n_fac="f999">
<datos_empresa>
    <nombre>Equipos Digitales S.L.</nombre>
    <dir>Av. Valladolid</dir>
    <poblacion>Madrid</poblacion>
    <codigo_postal>28043</codigo_postal>
    <provincia>Madrid</provincia>
    <cif>Q-9876543</cif>
    <telefono>917776688</telefono>
    <fax>917776699</fax>
</datos_empresa>
<datos_cliente n_cli="c879">
    <nombre>Darío, Bueno Gutiérrez</nombre>
    <dir_env>Av. Oporto nº7 4ºd</dir_env>
    <poblacion>Madrid</poblacion>
    <codigo_postal>28043</codigo_postal>
    <provincia>Madrid</provincia>
</datos_cliente>
<datos_factura n_ped="p731" iva="16" f_pago= "efectivo" moneda="euro">
    <fecha>12-01-2005</fecha>
    <linea>
        <referencia>MII93000F/8</referencia>
        <descripcion>MICRO PENTIUM IV 3000MHZ FB800</descripcion>
        <cantidad>1</cantidad>
        <precio>230</precio>
        <importe>266,80</importe>
    </linea>
    <linea>
        <referencia>MB8QDIP4</referencia>
        <descripcion>PLACA BASE QDI P4</descripcion>
        <cantidad>1</cantidad>
        <precio>180</precio>
        <importe>208,80</importe>
    </linea>
    <linea>
        <referencia>MEDD512M32</referencia>
        <descripcion>DIMM DDR 512MB 3200</descripcion>
        <cantidad>2</cantidad>
        <precio>40</precio>
        <importe>92,80</importe>
    </linea>
    <linea>
        <referencia>HD250GSA7</referencia>
        <descripcion>DISCO DURO 250GB S-ATA 7200</descripcion>
        <cantidad>4</cantidad>
        <precio>120</precio>
        <importe>556,80</importe>
    </linea>
    <base>970,00</base>
    <cuota_iva>155,20</cuota_iva>
    <total>1125,20</total>
</datos_factura>
</factura>
</facturaTipo>
